# Generated by Django 4.1 on 2022-09-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0005_alter_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
